StochHMM: MotifScorer.cpp File Reference
MotifScorer.cpp File Reference
#include <iostream>
#include <fstream>
#include "emm.h"
#include "sequence.h"
#include "sequences.h"
#include "seqTracks.h"
#include "pwm.h"
#include "MotifScorer.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
Definition at line 21 of file MotifScorer.cpp.
References StochHMM::sequences::getFastas(), StochHMM::PWM::getTrack(), StochHMM::PWM::import(), and StochHMM::PWM::score().
{
        PWM mat;
        //mat.import("RSS23standard.txt");
        mat.import("Heptamer.txt");
        //std::cout << mat.stringify() << std::endl;
        sequences seqs;
        seqs.getFastas("chr22.fa",mat.getTrack());
        mat.score(&seqs);
//      seqs.addSeq(sq, mat.getTrack());
//
//      mat.score(&seqs);
        //mat.score(sq);
        //std::cout << sq->getHeader() << std::endl;
}