StochHMM: StochHMM.cpp File Reference
StochHMM.cpp File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <iomanip>
#include <time.h>
#include <fstream>
#include "StochHMMlib.h"
#include "StochHMM_usage.h"
Macros
#define STATE_MAX 1024
Functions
void import_model (model &)
void import_sequence (model &)
void perform_viterbi_decoding (model *hmm, sequences *seqs)
void perform_nbest_decoding (model *hmm, sequences *seqs)
void perform_posterior (model *hmm, sequences *seqs)
void perform_stochastic_decoding (model *hmm, sequences *seqs)
void print_output (multiTraceback *, std::string &)
void print_output (std::vector< traceback_path > &, std::string &)
void print_output (traceback_path *, std::string &)
void print_posterior (trellis &)
int main (int argc, const char *argv[])
Variables
opt_parameters commandline []
int opt_size = sizeof(commandline)/sizeof(commandline[0])
options opt
seqTracks jobs
StateFuncs default_functions
Macro Definition Documentation
#define STATE_MAX 1024
Definition at line 38 of file StochHMM.cpp.
Function Documentation
void import_model (model & hmm)
Definition at line 210 of file StochHMM.cpp.
References default_functions, StochHMM::model::import(), StochHMM::options::isFlagSet(), StochHMM::options::isSet(), opt, StochHMM::model::print(), StochHMM::options::sopt(), and usage.
Referenced by main().
{
    if (!opt.isSet("-model")){
        std::cerr <<"No model file provided.\n" << usage << std::endl;
    }
    else{
                //Import the model using string supplied from commandline
                //Pass StateFuncs.   This will allow the user to define
                //the functions within the model.
                hmm.import(opt.sopt("-model"),&default_functions);
    }
    //If -debug model is defined then print model to stdout;
    if (opt.isFlagSet("-debug","model")){
        hmm.print();
    }
}
void import_sequence (model & hmm)
Definition at line 230 of file StochHMM.cpp.
References StochHMM::FASTA, StochHMM::FASTQ, StochHMM::options::isSet(), jobs, StochHMM::seqTracks::loadSeqs(), opt, StochHMM::options::sopt(), and usage.
Referenced by main().
{
    if (!opt.isSet("-seq")){
        std::cerr << "No sequence file provided.\n" << usage << std::endl;
    }
        else if (opt.isSet("-fastq")){
                //Fastq import is still preliminary, it will only
                //import the sequence, not the qualities
                jobs.loadSeqs(hmm,opt.sopt("-seq"),FASTQ);
        }
    else{
                //Import the sequence form fasta file
        jobs.loadSeqs(hmm, opt.sopt("-seq"), FASTA);
    }
}
int main (int argc, const char * argv[])
Definition at line 95 of file StochHMM.cpp.
References commandline, StochHMM::seqTracks::getJob(), StochHMM::seqJob::getModel(), StochHMM::options::getopt(), StochHMM::seqJob::getSeqs(), import_model(), import_sequence(), StochHMM::options::isFlagSet(), StochHMM::options::isSet(), jobs, opt, opt_size, StochHMM::options::parse_commandline(), perform_nbest_decoding(), perform_posterior(), perform_stochastic_decoding(), perform_viterbi_decoding(), StochHMM::sequences::print(), StochHMM::options::set_parameters(), and usage.
{
    //Parse commandline arguments defined
    opt.set_parameters(commandline,opt_size,usage);
        //Get and parse command line options supplied by user
    opt.parse_commandline(argc,argv);
        //Create a model
    model hmm;
    //import the model
    import_model(hmm);
//      if (opt.isFlagSet("-debug", "paths")){
//              hmm.writeGraphViz("Model_Path-debug.viz", true);
//      }
    //Check and import sequence(s)
        //These will be imported into seqTracks jobs
    import_sequence(hmm);
        //Get the job (model and associated sequences)
    seqJob *job=jobs.getJob();
        //If filename is set for any of the following
        //options we need to re-direct the stdout to the file
        std::string filename;
        if (opt.isSet("-posterior")){
                opt.getopt("-posterior",filename);
        }
        else if (opt.isSet("-gff")){
                opt.getopt("-gff", filename);
        }
        else if (opt.isSet("-path")){
                opt.getopt("-path", filename);
        }
        else if (opt.isSet("-label")){
                opt.getopt("-label", filename);
        }
        //Create file handle
        std::ofstream file;
        //Create ptr to store STDOUT if we redirect
        std::streambuf* oldCoutStream(NULL);
        bool file_open(false);
        //If we defined a filename then redirect stdout
        if (!filename.empty()){
                oldCoutStream = std::cout.rdbuf();
                file.open(filename.c_str());
                std::cout << std::setprecision(3);
                std::cout << std::fixed;
                if (!file.is_open()){
                        std::cerr << "Couldn't open file for posterior" << std::endl;
                        exit(1);
                }
                file_open = true;
                std::cout.rdbuf(file.rdbuf());
        }
        // Fore each job(sequence) perform the analysis
        while (job != NULL){
                //Print sequences if -debug seq option defined
                if (opt.isFlagSet("-debug","seq")){
                        job->getSeqs()->print();
                }
                //Perform posterior analysis
                if (opt.isSet("-posterior")){
                        perform_posterior(&hmm, job->getSeqs());
                }
                //Perform viterbi analysis
                else if(opt.isSet("-viterbi")){
                        perform_viterbi_decoding(job->getModel(), job->getSeqs());
                }
                //Perform nbest Viterbi decoding
                else if (opt.isSet("-nbest")){
                        perform_nbest_decoding(job->getModel(), job->getSeqs());
                }
                //Perform stochastic decoding
                else if (opt.isSet("-stochastic")){
                        perform_stochastic_decoding(job->getModel(), job->getSeqs());
                }
                //Get next job
                job = jobs.getJob();
        }
        //Close file and redirect stdout to original place
        if (file_open){
                std::cout.rdbuf(oldCoutStream);
                file.close();
        }
    return 0;
}
void perform_nbest_decoding (model * hmm, sequences * seqs)
Definition at line 266 of file StochHMM.cpp.
References StochHMM::sequences::getHeader(), StochHMM::options::iopt(), StochHMM::trellis::naive_nth_viterbi(), opt, print_output(), and StochHMM::trellis::traceback_nth().
Referenced by main().
{
        //Setup the trellis with the model and sequence
        trellis trell(hmm,seqs);
        //Get the number of paths to get
        size_t nth = opt.iopt("-nbest");
        //Perform nth viterbi
        trell.naive_nth_viterbi(nth);
        //Get the N tracebacks and output them
        for(size_t i=0;i<nth;i++){
                traceback_path path(hmm);
                trell.traceback_nth(path, i); //ith path
                print_output(&path, seqs->getHeader());
        }
}
void perform_posterior (model * hmm, sequences * seqs)
Definition at line 329 of file StochHMM.cpp.
References StochHMM::sequences::getHeader(), StochHMM::options::isSet(), opt, StochHMM::trellis::posterior(), print_output(), print_posterior(), and StochHMM::trellis::traceback_posterior().
Referenced by main().
{
        trellis trell(hmm,seqs);
        //TODO: posterior should check model and choose the appropriate algorithm
        trell.posterior();
        //If we need a posterior traceback b/c path,label,or GFF is defined
        if (opt.isSet("-gff") || opt.isSet("-path") || opt.isSet("-label")){
                traceback_path path(hmm);
                trell.traceback_posterior(path);
                print_output(&path, seqs->getHeader());
        }
        else{
                print_posterior(trell);
        }
        return;
}
void perform_stochastic_decoding (model * hmm, sequences * seqs)
Definition at line 286 of file StochHMM.cpp.
References StochHMM::sequences::getHeader(), StochHMM::options::iopt(), StochHMM::options::isFlagSet(), StochHMM::options::isSet(), opt, StochHMM::trellis::posterior(), print_output(), StochHMM::trellis::stochastic_forward(), StochHMM::trellis::stochastic_traceback(), StochHMM::trellis::stochastic_viterbi(), StochHMM::trellis::traceback_stoch_posterior(), and usage.
Referenced by main().
{
    //Determine which type of stochastic algorithm to perform
    bool viterbi        = (opt.isFlagSet("-stochastic", "viterbi") || opt.isSet("-viterbi")) ? true : false;
    bool forward        = (opt.isFlagSet("-stochastic", "forward")) ? true : false;
    bool posterior      = (opt.isFlagSet("-stochastic", "posterior")) ? true : false;
        //Setup the trellis with the model and sequence
    trellis trell(hmm,seqs);
        //Number of times to traceback over path
        int repetitions = opt.iopt("-rep");
    if (viterbi){
                trell.stochastic_viterbi();
                //create multiple paths object to stor
                multiTraceback paths;
                trell.stochastic_traceback(paths, repetitions);
                print_output(&paths, seqs->getHeader());
    }
    else if (forward){
                trell.stochastic_forward();
                multiTraceback paths;
                trell.stochastic_traceback(paths, repetitions);
                print_output(&paths, seqs->getHeader());
    }
        else if (posterior){
                trell.posterior();
                multiTraceback paths;
                trell.traceback_stoch_posterior(paths, repetitions);
                print_output(&paths, seqs->getHeader());
        }
    else{
        std::cerr << usage << "\nNo Stochastic decoding option set\n";
        return;
    }
    return;
}
void perform_viterbi_decoding (model * hmm, sequences * seqs)
Definition at line 247 of file StochHMM.cpp.
References StochHMM::sequences::getHeader(), print_output(), StochHMM::trellis::traceback(), and StochHMM::trellis::viterbi().
Referenced by main().
{
        //Setup the trellis with the model and sequence
    trellis trell(hmm,seqs);
        //Perform viterbi decoding
        trell.viterbi();
        //Create a traceback path ptr to store traceback from perform_traceback
        //function
        traceback_path path(hmm);
        trell.traceback(path);
        //Call print_output (below) to print the traceback in the required format
        print_output(&path, seqs->getHeader());
    return;
}
void print_output (multiTraceback * tb, std::string & header)
Definition at line 350 of file StochHMM.cpp.
References StochHMM::multiTraceback::finalize(), StochHMM::options::isSet(), opt, StochHMM::multiTraceback::print_gff(), StochHMM::multiTraceback::print_hits(), StochHMM::multiTraceback::print_label(), and StochHMM::multiTraceback::print_path().
Referenced by perform_nbest_decoding(), perform_posterior(), perform_stochastic_decoding(), and perform_viterbi_decoding().
{
    tb->finalize();
    bool previous(true);
    if (opt.isSet("-hits")){
        tb->print_hits();
        previous=false;
    }
    if (opt.isSet("-gff")){
        tb->print_gff(header);
        previous=false;
    }
    if (opt.isSet("-label")){
        tb->print_label();
        previous=false;
    }
    //Print path by default if nothing else is set
    if (opt.isSet("-path") || previous){
        tb->print_path();
    }
}
void print_output (std::vector< traceback_path > & , std::string &)
void print_output (traceback_path * tb, std::string & header)
Definition at line 378 of file StochHMM.cpp.
References StochHMM::traceback_path::getScore(), StochHMM::options::isSet(), opt, StochHMM::traceback_path::print_gff(), StochHMM::traceback_path::print_label(), and StochHMM::traceback_path::print_path().
{
    bool previous(true);
    if (opt.isSet("-gff")){
        std::cout << "Score: " << tb->getScore() << std::endl;
        tb->print_gff(header);
        previous=false;
    }
    if (opt.isSet("-label")){
                std::cout << ">" << header ;
        std::cout << "\tScore: " << tb->getScore() << std::endl;
        tb->print_label();
        previous=false;
    }
    if (opt.isSet("-path") || previous){
                std::cout << ">" << header ;
        std::cout << "\tScore: " << tb->getScore() << std::endl;
        tb->print_path();
    }
    return;
}
void print_posterior (trellis & trell)
Definition at line 408 of file StochHMM.cpp.
References StochHMM::trellis::getBackwardProbability(), StochHMM::trellis::getForwardProbability(), StochHMM::sequences::getHeader(), StochHMM::trellis::getModel(), StochHMM::model::getName(), StochHMM::trellis::getPosteriorTable(), StochHMM::trellis::getSeq(), StochHMM::model::getStateName(), and StochHMM::model::state_size().
Referenced by perform_posterior().
{
        model* hmm = trell.getModel();
        double_2D* table = trell.getPosteriorTable();
        size_t state_size = hmm->state_size();
        char cstr[200];
        std::string output;
        output+="Posterior Probabilities Table\n";
        output+="Model:\t" + hmm->getName() + "\n";
        output+="Sequence:\t" + trell.getSeq()->getHeader() + "\n";
        sprintf(cstr, "Probability of Sequence from Forward: Natural Log'd\t%f\n",trell.getForwardProbability());
        output+= cstr;
        sprintf(cstr, "Probability of Sequence from Backward:Natural Log'd\t%f\n",trell.getBackwardProbability());
        output+= cstr;
        output+= "Position";
        for(size_t i=0;i< state_size; ++i){
                output+= "\t" + hmm->getStateName(i);
        }
        output+="\n";
        std::cout <<  output;
        for(size_t position = 0; position < table->size(); ++position){
                sprintf(cstr, "%ld", position+1);
                output= cstr;
                for (size_t st = 0 ; st < state_size ; st++){
                        float val  = exp((*table)[position][st]);
                        if (val<= 0.001){
                                output+="\t0";
                        }
                        else if (val == 1.0){
                                output+="\t1";
                        }
                        else{
                                sprintf(cstr,"\t%.3f", exp((*table)[position][st]));
                                output+= cstr;
                        }
                }
                output+="\n";
                std::cout << output;
        }
        std::cout << std::endl;
        return;
}
Variable Documentation
opt_parameters commandline[]
Initial value:
{
    {"-help:-h"     ,OPT_NONE       ,false  ,"",    {}},
    {"-model:-m"    ,OPT_STRING     ,true   ,"",    {}},
    {"-seq:-s:-track",OPT_STRING    ,true   ,"",    {}},
        {"-fastq"               ,OPT_NONE               ,false  ,"",    {}},
    {"-debug:-d"    ,OPT_FLAG           ,false  ,"",    {"model","seq","paths"}},
    {"-viterbi"     ,OPT_NONE       ,false  ,"",    {}},
        {"-nbest"       ,OPT_INT        ,false  ,"3",   {}},
    {"-posterior"   ,OPT_STRING         ,false  ,"",    {}},
    {"-stochastic"  ,OPT_FLAG       ,false  ,"",    {"viterbi","forward","posterior"}},
    {"-repetitions:-rep",OPT_INT    ,false  ,"1000",{}},
    {"-gff:-g"      ,OPT_STRING     ,false  ,"",    {}},
    {"-path:-p"     ,OPT_STRING     ,false  ,"",    {}},
    {"-label:-l"    ,OPT_STRING     ,false  ,"",    {}},
        {"-hits"        ,OPT_STRING     ,false  ,"",    {}},
    {"-trellis"     ,OPT_STRING     ,false  ,"",    {}},
}
Definition at line 56 of file StochHMM.cpp.
Referenced by main().
StateFuncs default_functions
Definition at line 92 of file StochHMM.cpp.
Referenced by import_model().
seqTracks jobs
Definition at line 87 of file StochHMM.cpp.
Referenced by import_sequence(), and main().
options opt
Definition at line 84 of file StochHMM.cpp.
Referenced by import_model(), import_sequence(), main(), perform_nbest_decoding(), perform_posterior(), perform_stochastic_decoding(), and print_output().
int opt_size = sizeof(commandline)/sizeof(commandline[0])
Definition at line 81 of file StochHMM.cpp.
Referenced by main().