StochHMM: StochHMM::multiTraceback Class Reference
StochHMM::multiTraceback Class Reference
#include <traceback_path.h>
Public Member Functions
multiTraceback ()
Create multiTraceback()
~multiTraceback ()
Destroy multiTraceback.
void begin ()
Set position in multiTraceback to the beginning.
void end ()
Set position in multiTraceback to the ending.
void operator++ ()
Increment the iterator to next position.
void operator-- ()
Decrement the iterator to previous position.
void operator= (size_t)
void print_path ()
void print_label ()
void print_gff (std::string &)
void print_hits ()
traceback_path path ()
Get traceback_path at currently set index in multiTraceback.
int counts ()
Get the number times that traceback_path was recorded in multiple traceback.
traceback_path operator[] (size_t)
void assign (traceback_path &)
void finalize ()
Sorts the multiTraceback by the number of time a particular tracback path occurred.
void clear ()
size_t size ()
heatTable * get_hit_table ()
Private Attributes
size_t vectorIterator
size_t maxSize
std::vector< std::map
< traceback_path, int >
::iterator > pathAccess
std::map< traceback_path, int > paths
heatTable * table
Detailed Description
Contains multiple tracebacks. Will store them in sorted unique list (sorted in order of number of occurances);
Definition at line 168 of file traceback_path.h.
Constructor & Destructor Documentation
StochHMM::multiTraceback::multiTraceback ()
Create multiTraceback()
Definition at line 401 of file traceback_path.cpp.
References maxSize, and vectorIterator.
{
        maxSize=0;
        vectorIterator=0;
        table=NULL;
    }
StochHMM::multiTraceback::~multiTraceback ()
Destroy multiTraceback.
Definition at line 408 of file traceback_path.cpp.
References table.
{
        if(table!=NULL){
            delete table;
        }
    }
Member Function Documentation
void StochHMM::multiTraceback::assign (traceback_path & path)
Add traceback_path to multiTraceback
Parameters:
path Traceback path to add
Definition at line 472 of file traceback_path.cpp.
References path(), and paths.
Referenced by StochHMM::trellis::stochastic_traceback(), and StochHMM::trellis::traceback_stoch_posterior().
{
        paths[path]++;
        return;
    }
void StochHMM::multiTraceback::begin ()
Set position in multiTraceback to the beginning.
Definition at line 415 of file traceback_path.cpp.
References vectorIterator.
{
        vectorIterator=0;
        return;
    }
void StochHMM::multiTraceback::clear () inline
Definition at line 199 of file traceback_path.h.
References paths.
{paths.clear();return;};
int StochHMM::multiTraceback::counts ()
Get the number times that traceback_path was recorded in multiple traceback.
Definition at line 465 of file traceback_path.cpp.
References pathAccess, and vectorIterator.
{
        return (*pathAccess[vectorIterator]).second;
    }
void StochHMM::multiTraceback::end ()
Set position in multiTraceback to the ending.
Definition at line 421 of file traceback_path.cpp.
References paths, and vectorIterator.
{
        vectorIterator=paths.size();
        return;
    }
void StochHMM::multiTraceback::finalize ()
Sorts the multiTraceback by the number of time a particular tracback path occurred.
Definition at line 479 of file traceback_path.cpp.
References maxSize, pathAccess, paths, StochHMM::sortTBVec(), and vectorIterator.
Referenced by print_gff(), print_label(), print_output(), and print_path().
{
        maxSize=paths.size();
        vectorIterator=0;
        std::map<traceback_path,int>::iterator pathsIterator;
        for(pathsIterator=paths.begin();pathsIterator!=paths.end();pathsIterator++){
            pathAccess.push_back(pathsIterator);
        }
        sort(pathAccess.begin(),pathAccess.end(),sortTBVec);
        return;
    }
heatTable * StochHMM::multiTraceback::get_hit_table ()
Generate a hit table from a multiple traceback paths Hit table is 2D table describing how many times a state was called at a particular position in the sequence
Definition at line 494 of file traceback_path.cpp.
References pathAccess, paths, StochHMM::model::state_size(), and table.
Referenced by print_hits().
{
        if (table!=NULL){
            delete table;
        }
        //Over the lenght of the sequence
        model* hmm = ((*pathAccess[0]).first).getModel();
        size_t sequenceSize=((*pathAccess[0]).first).size();
        size_t stateSize=hmm->state_size();
        std::vector<int> states(stateSize,0);
        table = new heatTable(sequenceSize,states);
        std::map<traceback_path,int>::iterator it;
        for( it =paths.begin(); it!=paths.end();it++){
            int count = (*it).second;
            for(size_t position=0;position<sequenceSize;position++){
                int tbState=(*it).first[position];
                (*table)[position][tbState]+=count;
            }
        }
        return table;
    }
void StochHMM::multiTraceback::operator++ ()
Increment the iterator to next position.
Definition at line 427 of file traceback_path.cpp.
References maxSize, and vectorIterator.
{
        if (vectorIterator<maxSize){
            vectorIterator++;
        }
        return;
    }
void StochHMM::multiTraceback::operator-- ()
Decrement the iterator to previous position.
Definition at line 435 of file traceback_path.cpp.
References vectorIterator.
{
        if (vectorIterator>0){
            vectorIterator--;
        }
        return;
    }
void StochHMM::multiTraceback::operator= (size_t val)
Set iterator to index val
Parameters:
val Index value to set
Definition at line 444 of file traceback_path.cpp.
References maxSize, and vectorIterator.
{
        if (val<=maxSize){
            vectorIterator=val;
        }
        return;
    }
traceback_path StochHMM::multiTraceback::operator[] (size_t val)
Get traceback_path at index position
Parameters:
val Index position
Definition at line 454 of file traceback_path.cpp.
References pathAccess.
{
        return (*pathAccess[val]).first;
    }
traceback_path StochHMM::multiTraceback::path ()
Get traceback_path at currently set index in multiTraceback.
Definition at line 460 of file traceback_path.cpp.
References pathAccess, and vectorIterator.
Referenced by assign().
{
        return (*pathAccess[vectorIterator]).first;
    }
void StochHMM::multiTraceback::print_gff (std::string & header)
Definition at line 564 of file traceback_path.cpp.
References finalize(), pathAccess, and size().
Referenced by print_output().
{
        this->finalize();
        for(size_t iter=0; iter<this->size(); iter++){
            std::cout << "Traceback occurred:\t " << (*pathAccess[iter]).second << std::endl;
            (*pathAccess[iter]).first.print_gff(header);
            std::cout << std::endl;
        }
        return;
    }
void StochHMM::multiTraceback::print_hits ()
Definition at line 521 of file traceback_path.cpp.
References get_hit_table(), StochHMM::model::getStateName(), StochHMM::join(), pathAccess, and StochHMM::model::state_size().
Referenced by print_output().
{
        if (table==NULL){
            get_hit_table();
        }
        std::string header_row = "Position";
        model* hmm = ((*pathAccess[0]).first).getModel();
        for (size_t state_iter =0; state_iter<hmm->state_size(); state_iter++){
            header_row+=",";
            header_row+=hmm->getStateName(state_iter);
        }
        std::cout << header_row << std::endl;
        for(size_t position = 0; position < table->size(); position++){
            std::string line = join((*table)[position], ',');
            std::cout << position << "," << line << std::endl;
        }
        return;
    }
void StochHMM::multiTraceback::print_label ()
Definition at line 554 of file traceback_path.cpp.
References finalize(), pathAccess, and size().
Referenced by print_output().
{
        this->finalize();
        for(size_t iter=0; iter<this->size(); iter++){
            std::cout << "Traceback occurred:\t " << (*pathAccess[iter]).second << std::endl;
            (*pathAccess[iter]).first.print_label();
            std::cout << std::endl;
        }
        return;
    }
void StochHMM::multiTraceback::print_path ()
Definition at line 544 of file traceback_path.cpp.
References finalize(), pathAccess, and size().
Referenced by print_output().
{
        this->finalize();
        for(size_t iter=0; iter<this->size(); iter++){
            std::cout << "Traceback occurred:\t " << (*pathAccess[iter]).second << std::endl;
            (*pathAccess[iter]).first.print_path();
            std::cout << std::endl;
        }
        return;
    }
size_t StochHMM::multiTraceback::size (void) inline
Definition at line 200 of file traceback_path.h.
References paths.
Referenced by print_gff(), print_label(), and print_path().
{return paths.size();};
Member Data Documentation
size_t StochHMM::multiTraceback::maxSize private
Definition at line 206 of file traceback_path.h.
Referenced by finalize(), multiTraceback(), operator++(), and operator=().
std::vector<std::map<traceback_path,int>::iterator> StochHMM::multiTraceback::pathAccess private
Definition at line 207 of file traceback_path.h.
Referenced by counts(), finalize(), get_hit_table(), operator[](), path(), print_gff(), print_hits(), print_label(), and print_path().
std::map<traceback_path,int> StochHMM::multiTraceback::paths private
Definition at line 208 of file traceback_path.h.
Referenced by assign(), clear(), end(), finalize(), get_hit_table(), and size().
heatTable* StochHMM::multiTraceback::table private
Definition at line 209 of file traceback_path.h.
Referenced by get_hit_table(), and ~multiTraceback().
size_t StochHMM::multiTraceback::vectorIterator private
Definition at line 205 of file traceback_path.h.
Referenced by begin(), counts(), end(), finalize(), multiTraceback(), operator++(), operator--(), operator=(), and path().
The documentation for this class was generated from the following files:
traceback_path.h
traceback_path.cpp