StochHMM: StochHMM::matrixPosition Class Reference
StochHMM::matrixPosition Class Reference
#include <pwm.h>
Public Member Functions
bool parse (std::string &txt, track *trk, stringList &names)
float getEmissionValue (sequences *, size_t)
float getEmissionValue (sequence *, size_t)
emm * getEmission ()
void addTransition (emm *trans)
std::vector< std::string > & getTransitionNames ()
void setThreshold (float thresh)
float * getThresholdPtr ()
float getThreshold ()
size_t transitionsSize ()
bool isThresholdSet ()
std::string stringify ()
Detailed Description
Stores weight information for a position in the position weight matrix
Definition at line 122 of file pwm.h.
Member Function Documentation
bool StochHMM::matrixPosition::parse (std::string & txt, track * trk, stringList & names)
Parses the emission for each position from a string
Parameters:
txt String representation of emissions
names stringList of all state names defined in the model
trks Tracks defined in the model
wts Weight defined of the model
funcs StateFunction defined for the model
Definition at line 235 of file pwm.cpp.
References StochHMM::clear_whitespace(), StochHMM::emm::parse(), StochHMM::stringList::size(), StochHMM::stringList::splitND(), and StochHMM::stringList::splitString().
{
                size_t nameHeader = txt.find("NAME:");
                size_t transHeader = txt.find("TRANSITION:");
                size_t thresholdHeader = txt.find("THRESHOLD:");
                //size_t emmHeader = txt.find("EMISSION:");
                size_t end = txt.find("//END");
                if (end != std::string::npos){
                        txt = txt.substr(0,end);
                }
                //Parse Name
                if (nameHeader != std::string::npos){
                        size_t endline = txt.find("\n",nameHeader);
                        std::string temp_name = txt.substr(nameHeader,endline-nameHeader);
                        stringList tmp;
                        tmp.splitString(temp_name, ":");
                        clear_whitespace(tmp[1], "\t\n ");
                        name = tmp[1];
                }
                else{
                        std::cerr << "Position is missing NAME definition\n"<< txt << std::endl;
                        exit(2);
                }
                //Parse Transitions
                if (transHeader != std::string::npos){
                        std::string temp;
                        size_t endline = txt.find("\n",transHeader);
                        temp = txt.substr(transHeader, endline - transHeader);
                        stringList transi;
                        transi.splitString(temp,":,");
                        for(size_t i = 1; i < transi.size(); i++){
                                clear_whitespace(transi[i], " \t\n");
                                transition_names.push_back(transi[i]);
                        }
                }
                //Parse Thresholds
                if (thresholdHeader != std::string::npos){
                        size_t endline = txt.find("\n",thresholdHeader);
                        std::string temp = txt.substr(thresholdHeader, endline-thresholdHeader);
                        stringList tmp;
                        tmp.splitString(temp, ":");
                        clear_whitespace(tmp[1], "\t\n ");
                        threshold = atof(tmp[1].c_str());
                        thresholdSet = true;
                }
        stringList lst;
        lst.splitND(txt,"EMISSION:");
                emm* temp_emm = new(std::nothrow) emm;
                if (temp_emm==NULL){
                        std::cerr << "OUT OF MEMORY\nFile" << __FILE__ << "Line:\t"<< __LINE__ << std::endl;
                        exit(1);
                }
                if (!temp_emm->parse(lst[0],trk)){
                        return false;
                }
                positionMatrix = temp_emm;
        return true;
    }
The documentation for this class was generated from the following files:
pwm.h
pwm.cpp