StochHMM: StochHMM::cell Class Reference
StochHMM::cell Class Reference
#include <alignment.h>
Public Member Functions
cell ()
void setTraceback (tracebackDirection dir)
void setScore (double value)
void setDiag (double value)
void setLeft (double value)
void setUp (double value)
double getScore ()
tracebackDirection getTraceback ()
Private Attributes
tracebackDirection traceback
double score
std::vector< double > scores
Detailed Description
Definition at line 28 of file alignment.h.
Constructor & Destructor Documentation
StochHMM::cell::cell ()
Definition at line 14 of file alignment.cpp.
References scores.
              :traceback(NONE),score(0.0){
        scores.insert(scores.begin(),3,0.0);
    }
Member Function Documentation
double StochHMM::cell::getScore () inline
Definition at line 36 of file alignment.h.
References score.
{return score;}
tracebackDirection StochHMM::cell::getTraceback () inline
Definition at line 37 of file alignment.h.
References traceback.
{return traceback;}
void StochHMM::cell::setDiag (double value) inline
Definition at line 33 of file alignment.h.
References scores.
Referenced by StochHMM::alignment::_initTrellis().
{scores[0]=value;}
void StochHMM::cell::setLeft (double value) inline
Definition at line 34 of file alignment.h.
References scores.
Referenced by StochHMM::alignment::_initTrellis().
{scores[1]=value;}
void StochHMM::cell::setScore (double value) inline
Definition at line 32 of file alignment.h.
References score.
Referenced by StochHMM::alignment::_initTrellis().
{score=value;}
void StochHMM::cell::setTraceback (tracebackDirection dir) inline
Definition at line 31 of file alignment.h.
References traceback.
Referenced by StochHMM::alignment::_initTrellis().
{traceback = dir;}
void StochHMM::cell::setUp (double value) inline
Definition at line 35 of file alignment.h.
References scores.
Referenced by StochHMM::alignment::_initTrellis().
{scores[2]=value;}
Member Data Documentation
double StochHMM::cell::score private
Definition at line 40 of file alignment.h.
Referenced by getScore(), and setScore().
std::vector<double> StochHMM::cell::scores private
Definition at line 41 of file alignment.h.
Referenced by cell(), setDiag(), setLeft(), and setUp().
tracebackDirection StochHMM::cell::traceback private
Definition at line 39 of file alignment.h.
Referenced by getTraceback(), and setTraceback().
The documentation for this class was generated from the following files:
alignment.h
alignment.cpp