StochHMM: Probability Density Functions
Probability Density Functions
Functions
double StochHMM::binomial_pdf (int k, int n, double p)
double StochHMM::binomial_pdf (int k, std::vector< double > param)
double StochHMM::beta_binomial_pdf (int k, int n, double a, double b)
double StochHMM::degenerate_pdf (double value, double k)
double StochHMM::discrete_uniform_pdf (int position, int a, int b)
double StochHMM::hypergeometric_pdf (int k, int n, int N, int m)
double StochHMM::poisson_binomial_pdf (int k, std::vector< double > &p)
double StochHMM::beta_negative_binomial_pdf (int k, int n, double a, double b)
double StochHMM::maxwell_boltzman_pdf (double x, double a)
double StochHMM::geometric_pdf (int k, double p)
double StochHMM::logarithmic_pdf (int k, double p)
double StochHMM::negative_binomial_pdf (int k, int r, double p)
double StochHMM::poisson_pdf (int k, double lambda)
double StochHMM::yule_simon_pdf (int k, double p)
double StochHMM::zipf_pdf (int k, int N, double s)
double StochHMM::zipf_mandelbrot_pdf (int k, int N, double s, double q)
double StochHMM::arcsine_pdf (double x)
double StochHMM::beta_pdf (double x, double a, double b)
double StochHMM::beta_pdf (double x, std::vector< double > param)
double StochHMM::logit_normal_pdf (double x, double mu, double sigma)
double StochHMM::continuous_uniform_pdf (double x, double a, double b)
double StochHMM::kumaraswamy_pdf (double x, double a, double b)
double StochHMM::raised_cosine_pdf (double x, double mu, double s)
double StochHMM::triangular_pdf (double x, double a, double b, double c)
double StochHMM::truncated_normal_pdf (double x, double mu, double sd, double a, double b)
double StochHMM::u_quadratic_pdf (double x, double a, double b)
double StochHMM::wigner_semicircle_pdf (double x, double r)
double StochHMM::beta_prime_pdf (double x, double a, double b)
double StochHMM::chi_pdf (double x, double k)
double StochHMM::chi_squared_pdf (double x, double k)
double StochHMM::inverse_chi_squared_pdf (double x, double v)
double StochHMM::scaled_inverse_chi_squared_pdf (double x, double v, double sigma_sqrd)
double StochHMM::dagum_pdf (double x, double p, double a, double b)
double StochHMM::exponential_pdf (double x, double lambda)
double StochHMM::f_pdf (double x, double d1, double d2)
double StochHMM::fishers_z_pdf (double x, double d1, double d2)
double StochHMM::folded_normal_pdf (double x, double mu, double sigma_sqrd)
double StochHMM::frechet_pdf (double x, double alpha, double s, double m)
double StochHMM::gamma_pdf (double x, double alpha, double beta)
double StochHMM::inv_gamma_pdf (double x, double alpha, double beta)
double StochHMM::half_normal_pdf (double x, double sigma)
double StochHMM::inv_gaussian_pdf (double x, double mu, double lambda)
double StochHMM::levy_pdf (double x, double mu, double scale)
double StochHMM::log_cauchy_pdf (double x, double mu, double sigma)
double StochHMM::log_laplace_pdf (double x, double mu, double b)
double StochHMM::log_logistic_pdf (double x, double a, double b)
double StochHMM::log_normal_pdf (double x, double mu, double sigma_sqrd)
double StochHMM::pareto_pdf (double x, double alpha, double x_m)
double StochHMM::nakagami_pdf (double x, double mu, double w)
double StochHMM::rayleigh_pdf (double x, double sigma)
double StochHMM::gumbel_type_two_pdf (double x, double a, double b)
double StochHMM::weibull_distribution (double x, double lambda, double k)
double StochHMM::cauchy_pdf (double x, double x_o, double gamma)
double StochHMM::gumbel_pdf (double x, double mu, double beta)
double StochHMM::generalized_normal_pdf (double x, double mu, double alpha, double beta)
double StochHMM::hyperbolic_secant_pdf (double x)
double StochHMM::laplace_pdf (double x, double mu, double b)
double StochHMM::logistic_pdf (double x, double mu, double s)
double StochHMM::standard_normal_pdf (double x)
double StochHMM::normal_pdf (double x, double mu, double sigma)
double StochHMM::students_t_pdf (double x, double v)
double StochHMM::gumbel_type_one_pdf (double x, double a, double b)
double StochHMM::generalized_extreme_value_pdf (double x, double mu, double sigma, double xi)
double StochHMM::generalized_pareto_pdf (double x, double mu, double sigma, double xi)
double StochHMM::dirichlet_pdf (const std::vector< double > &x, const std::vector< double > &alpha)
double StochHMM::multivariate_ewens_pdf (const std::vector< double > &x, const double theta)
double StochHMM::binomial_pdf (const double k, const std::vector< double > *param)
double StochHMM::beta_binomial_pdf (const double k, const std::vector< double > *param)
double StochHMM::degenerate_pdf (const double value, const std::vector< double > *param)
double StochHMM::discrete_uniform_pdf (const double position, const std::vector< double > *param)
double StochHMM::hypergeometric_pdf (const double k, const std::vector< double > *param)
double StochHMM::beta_negative_binomial_pdf (const double k, const std::vector< double > *param)
double StochHMM::maxwell_boltzman_pdf (const double x, const std::vector< double > *param)
double StochHMM::geometric_pdf (const double k, const std::vector< double > *param)
double StochHMM::logarithmic_pdf (const double k, const std::vector< double > *param)
double StochHMM::negative_binomial_pdf (const double k, const std::vector< double > *param)
double StochHMM::poisson_pdf (const double k, const std::vector< double > *param)
double StochHMM::yule_simon_pdf (const double k, const std::vector< double > *param)
double StochHMM::zipf_pdf (const double k, const std::vector< double > *param)
double StochHMM::zipf_mandelbrot_pdf (const double k, const std::vector< double > *param)
double StochHMM::arcsine_pdf (const double x, const std::vector< double > *param)
double StochHMM::beta_pdf (const double x, const std::vector< double > *param)
double StochHMM::logit_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::continuous_uniform_pdf (const double x, const std::vector< double > *param)
double StochHMM::kumaraswamy_pdf (const double x, const std::vector< double > *param)
double StochHMM::raised_cosine_pdf (const double x, const std::vector< double > *param)
double StochHMM::triangular_pdf (const double x, const std::vector< double > *param)
double StochHMM::truncated_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::u_quadratic_pdf (const double x, const std::vector< double > *param)
double StochHMM::wigner_semicircle_pdf (const double x, const std::vector< double > *param)
double StochHMM::beta_prime_pdf (const double x, const std::vector< double > *param)
double StochHMM::chi_pdf (const double x, const std::vector< double > *param)
double StochHMM::chi_squared_pdf (const double x, const std::vector< double > *param)
double StochHMM::inverse_chi_squared_pdf (const double x, const std::vector< double > *param)
double StochHMM::scaled_inverse_chi_squared_pdf (const double x, const std::vector< double > *param)
double StochHMM::dagum_pdf (const double x, const std::vector< double > *param)
double StochHMM::exponential_pdf (const double x, const std::vector< double > *param)
double StochHMM::f_pdf (const double x, const std::vector< double > *param)
double StochHMM::fishers_z_pdf (const double x, const std::vector< double > *param)
double StochHMM::folded_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::frechet_pdf (const double x, const std::vector< double > *param)
double StochHMM::gamma_pdf (const double x, const std::vector< double > *param)
double StochHMM::inv_gamma_pdf (const double x, const std::vector< double > *param)
double StochHMM::half_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::inv_gaussian_pdf (const double x, const std::vector< double > *param)
double StochHMM::levy_pdf (const double x, const std::vector< double > *param)
double StochHMM::log_cauchy_pdf (const double x, const std::vector< double > *param)
double StochHMM::log_laplace_pdf (const double x, const std::vector< double > *param)
double StochHMM::log_logistic_pdf (const double x, const std::vector< double > *param)
double StochHMM::log_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::pareto_pdf (const double x, const std::vector< double > *param)
double StochHMM::nakagami_pdf (const double x, const std::vector< double > *param)
double StochHMM::rayleigh_pdf (const double x, const std::vector< double > *param)
double StochHMM::gumbel_type_two_pdf (const double x, const std::vector< double > *param)
double StochHMM::weibull_distribution (const double x, const std::vector< double > *param)
double StochHMM::cauchy_pdf (const double x, const std::vector< double > *param)
double StochHMM::gumbel_pdf (const double x, const std::vector< double > *param)
double StochHMM::generalized_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::hyperbolic_secant_pdf (const double x, const std::vector< double > *param)
double StochHMM::laplace_pdf (const double x, const std::vector< double > *param)
double StochHMM::logistic_pdf (const double x, const std::vector< double > *param)
double StochHMM::standard_normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::normal_pdf (const double x, const std::vector< double > *param)
double StochHMM::students_t_pdf (const double x, const std::vector< double > *param)
double StochHMM::gumbel_type_one_pdf (const double x, const std::vector< double > *param)
double StochHMM::generalized_extreme_value_pdf (const double x, const std::vector< double > *param)
double StochHMM::generalized_pareto_pdf (const double x, const std::vector< double > *param)
double StochHMM::dirichlet_multi_pdf (const std::vector< double > *x, const std::vector< double > *param)
double StochHMM::ewens_multi_pdf (const std::vector< double > *x, const std::vector< double > *param)
Detailed Description
Univariate and Multivariate probability density functions for use in continuous emissions.
Function Documentation
double StochHMM::arcsine_pdf (double x)
Arcsine probability distribution function
Parameters:
x value 0<=X<=1
Definition at line 242 of file PDF.cpp.
{
        if (x > 1.0 || x < 0.0 ){
            std::cerr << "Arcsine PDF: Incorrect parameters\n";
            exit(2);
        }
        return 1/(PI*sqrtf(x*(1-x)));
    }
double StochHMM::beta_binomial_pdf (int k, int n, double a, double b)
Beta-Binomial probability mass function Beta-binomial Model
Parameters:
k Value
n Number of trials
a alpha>0
b beta>0
Definition at line 32 of file PDF.cpp.
References StochHMM::bin_coef().
{
        double newAlpha = (double) k + a;
        double newBeta  = (double)(n-k) + b;
        return bin_coef(n,k) * (beta(newAlpha,newBeta)/ beta(a,b));
    }
double StochHMM::beta_negative_binomial_pdf (int k, int n, double a, double b)
Beta negative binomial pdf
Parameters:
k Value or number of failures to get N successes
n Number of successful trials
a Shape parameter
b Shape parameter
Definition at line 128 of file PDF.cpp.
References StochHMM::bin_coef().
{
        double pmf = bin_coef(n+k-1, k);
        pmf*=tgamma(a+n)*tgamma(b+k)*tgamma(a+b)/(tgamma(a+b+n+k)*tgamma(a)*tgamma(b));
        return pmf;
    }
double StochHMM::beta_pdf (double x, double a, double b)
Beta probability distribution function
Parameters:
x Value 0<x<1
a Shape parameter a>0
b Shape parameter b>0
Definition at line 255 of file PDF.cpp.
References StochHMM::betaPDF().
{
        if (x > 1.0 || x < 0.0 || a <= 0.0 || b <= 0.0){
            std::cerr << "Beta PDF: Incorrect parameters\n";
            exit(2);
        }
        return betaPDF(x, a, b);
    }
double StochHMM::beta_prime_pdf (double x, double a, double b)
Beta prime probability distribution function
Parameters:
x Value
a Alpha Shape parameter
b Beta Shape parameter
Definition at line 402 of file PDF.cpp.
{
        if (a<=0 || b<=0 || x<=0){
            std::cerr << "Beta prime PDF: Incorrect parameters\n";
            exit(2);
        }
        return (powf(x, a-1)*powf(1+x, -1*a-b))/ beta(a, b);
    }
double StochHMM::binomial_pdf (int k, int n, double p)
Binomial probability mass function Binomial Distribution
Parameters:
[in] k Number of successes
[in] n Number of trials
[in] p Probability of success
Returns:
P(X = k) = Probability of k successes in n trials
Definition at line 21 of file PDF.cpp.
References StochHMM::bin_coef().
Referenced by StochHMM::binomial_cdf(), and StochHMM::binomial_pdf().
{
        return bin_coef(n,k)*pow(p,k)*pow(1-p,n-k);
    }
double StochHMM::cauchy_pdf (double x, double x_o, double gamma)
Cauchy probability distribution function
Parameters:
x Value
x_o location parameter (place of peak)
gamma scale parameter gamma>0
Definition at line 749 of file PDF.cpp.
{
                if (gamma <= 0){
                        std::cerr << "Cauchy PDF: Incorrect parameters\n";
                        exit(2);
                }
                return (1/PI)* (gamma)/(pow(x-x_o, 2)+pow(gamma,2));
        }
double StochHMM::chi_pdf (double x, double k)
Chi probability distribution function
Parameters:
x Value x>=0
k degrees of freedom k>0
Definition at line 414 of file PDF.cpp.
{
        if (k<=0){
            std::cerr << "Chi PDF: Incorrect parameters\n";
            exit(2);
        }
        return (powf(2, 1-(k/2))*powf(x, k-1)*exp(-1*(powf(x, 2)/2)))/tgamma(k/2);
    }
double StochHMM::chi_squared_pdf (double x, double k)
Chi-squared probability distribution function
Parameters:
k K>0
x x>0
Definition at line 426 of file PDF.cpp.
{
        if ( k < 0 || x < 0){
            std::cerr << "Chi-squared PDF: Incorrect parameters\n";
            exit(2);
        }
        return (powf(x, (k/2)-1)*exp(-1*x/2))/(powf(2, k/2)*tgamma(k/2));
    }
double StochHMM::continuous_uniform_pdf (double x, double a, double b)
Continuous Uniform probability distribution function
Parameters:
x Value or Position to calculate
a Minimum position
b Maximum position
Definition at line 281 of file PDF.cpp.
{
        if (b<=a){
            std::cerr << "Continuous uniform PDF: Incorrect parameters\n";
            exit(2);
        }
        else if (x < a || x > b){
            return 0.0f;
        }
        else{
            return 1/(b-a);
        }
    }
double StochHMM::dagum_pdf (double x, double p, double a, double b)
Dagum probability distribution function
Parameters:
p Shape parameter p>0
a Shape parameter a>0
b Shape parameter b>0
x Value x>0
Definition at line 473 of file PDF.cpp.
{
        if ( p <= 0 || a <= 0 || b <= 0 || x <= 0){
            std::cerr << "Dagum PDF: Incorrect parameters\n";
            exit(2);
        }
        double pdf = (a*p)/x;
        pdf *= powf(x/b, a*p)/powf(powf(x/b, a)+1 , p+1);
        return pdf;
    }
double StochHMM::degenerate_pdf (double value, double k)
Degenerate probability mass function Degenerate Distribution
Parameters:
[in] value Current value
[in] k Degenerate value
Return values:
1 if value == k
0 if value !- k
Definition at line 44 of file PDF.cpp.
{
        if (value == k){
            return 1.0;
        }
        else{
            return 0.0;
        }
    }
double StochHMM::dirichlet_pdf (const std::vector< double > & x, const std::vector< double > & alpha)
Dirichlet Distribution
Parameters:
x Vector of values
alpha concentration parameters where a_i>0
Definition at line 921 of file PDF.cpp.
References StochHMM::sumVector().
{
                double gsum_alpha = tgamma(sumVector(alpha));
                //Calc product of gamma transformed alpha values
                double b_n(tgamma(alpha[0]));
                for (size_t i=1; i < alpha.size(); ++i){
                        b_n*=tgamma(alpha[i]);
                }
                double b = 1 / (b_n/gsum_alpha);  //Calculate B(alpha)
                //Calculate final value by finding product of xi^(ai-1)
                for (size_t i=0; i<alpha.size(); ++i){
                        b*=pow(x[i],alpha[i]-1);
                }
                return b;
        }
double StochHMM::discrete_uniform_pdf (int position, int a, int b)
Discrete Uniform probability mass function Uniform Distribution
Parameters:
position Value or Position to calculate
a Minimum position
b Maximum position
Return values:
1/(b-a+1) if position is between a and b
0 if position is outside of interval a to b
Definition at line 61 of file PDF.cpp.
{
        if (position<a || position>b){
            return 0;
        }
        else{
            return (double)1/(b-a+1);
        }
    }
double StochHMM::exponential_pdf (double x, double lambda)
Exponential probability distribution function
Parameters:
lambda Rate or Inverse scale lambda>0
x Value x>=0
Definition at line 487 of file PDF.cpp.
{
        if ( lambda <= 0 || x < 0 ){
            std::cerr << "Exponential PDF: Incorrect parameters\n";
            exit(2);
        }
        return lambda * exp (-1 * lambda * x);
    }
double StochHMM::f_pdf (double x, double d1, double d2)
F-Distribution
Parameters:
x Value x>=0
d1 Degree of freedom d1>0
d2 Degree of freedom d2>0
Definition at line 501 of file PDF.cpp.
{
        if (x < 0 || d1 <= 0 || d2 <= 0){
            std::cerr << "F Distribution PDF: Incorrect parameters\n";
            exit(2);
        }
        double numerator = sqrtf((powf(d1*x, d1)*powf(d2, d2))/powf(d1*x+d2, d1+d2));
        double denominator = x * beta(d1/2, d2/2);
        return numerator / denominator;
    }
double StochHMM::fishers_z_pdf (double x, double d1, double d2)
Fisher's z-distribution
Parameters:
x Value
d1 Degree of freedom d1>0
d2 Degree of freedom d2>0
Definition at line 516 of file PDF.cpp.
{
        if (d1 <= 0 || d2 <= 0){
            std::cerr << "Fisher's z-Distribution PDF: Incorrect parameters\n";
            exit(2);
        }
        double numerator = 2*powf(d1, d1/2)*powf(d2, d2/2)*exp(d1*x);
        double denominator = beta(d1/2, d2/2) * powf(d1*exp(2*x)+d2, (d1+d2)/2);
        return numerator/denominator;
    }
double StochHMM::folded_normal_pdf (double x, double mu, double sigma_sqrd)
Folded Normal probability distribution function
Parameters:
x Value x>=0
mu Mean(location)
sigma_sqrd Scale
Definition at line 531 of file PDF.cpp.
{
        if (x < 0 || sigma_sqrd <= 0 ){
            std::cerr << "Folded Normal PDF: Incorrect parameters\n";
            exit(2);
        }
        double l_pdf = 1/(sqrtf(sigma_sqrd*2 * PI));
        double l_temp = exp(-1* powf(-1*x-mu,2)/(2*sigma_sqrd));
        double r_temp = exp(-1* powf(x-mu,2)/(2*sigma_sqrd));
        return (l_pdf*l_temp) + (l_pdf *r_temp);
    }
double StochHMM::frechet_pdf (double x, double alpha, double s, double m)
Frechet Probability distribution function
Parameters:
x Value X>m
alpha Shape parameter a>0
s Scale parameter s>0 (default s=1)
m Location minimum (default m=0)
Definition at line 549 of file PDF.cpp.
{
        if (alpha <= 0 || s <= 0 || x < m ){
            std::cerr << "Frechet PDF: Incorrect parameters\n";
            exit(2);
        }
        return (alpha/s)*powf((x-m)/s, -1-alpha) * exp(-1*powf((x-m)/s, -1*alpha));
    }
double StochHMM::gamma_pdf (double x, double alpha, double beta)
Gamma probability distribution
Parameters:
x Value x>0
alpha Shape parameter a>0
beta Rate parameter b>0 *http://en.wikipedia.org/wiki/Gamma_distribution
Definition at line 563 of file PDF.cpp.
{
                if (x <= 0 ||  alpha <= 0 || beta <= 0){
                        std::cerr << "Gamma PDF: Incorrect parameters\n";
            exit(2);
                }
                return (pow(beta,alpha)/tgamma(alpha))*pow(x,alpha-1)*exp(-beta*x);
        }
double StochHMM::generalized_extreme_value_pdf (double x, double mu, double sigma, double xi)
Generalized extreme value probability distribution function
Parameters:
x Value;
mu location parameter
sigma scale parameter
xi shape parameter
Definition at line 868 of file PDF.cpp.
{
                if (sigma <= 0){
                        std::cerr << "Generalized extreme value PDF: Incorrect parameters\n";
                        exit(2);
                }
                if (xi > 0 && (x < mu - (sigma/xi) || x == INFINITY)){
                        std::cerr << "Generalized extreme value PDF: Incorrect parameters\n";
                        exit(2);
                }
                else if (xi == 0 && (x == -INFINITY || x == INFINITY)){
                        std::cerr << "Generalized extreme value PDF: Incorrect parameters\n";
                        exit(2);
                }
                else if (xi > 0 && (x == -INFINITY || x > mu - (sigma/xi))){
                        std::cerr << "Generalized extreme value PDF: Incorrect parameters\n";
                        exit(2);
                }
                double t = (xi == 0 ) ?  exp(-1*((x-mu)/sigma)) :  pow(1+((x-mu)/sigma)*xi, -1/xi);
                return (1/sigma)*pow(t,xi+1)*exp(-1*t);
        }
double StochHMM::generalized_normal_pdf (double x, double mu, double alpha, double beta)
Generalized Normal probability distribution function
Parameters:
x Value
mu Location parameter
alpha scale parameter alpha>0
beta shape parameter beta>0
Definition at line 791 of file PDF.cpp.
{
                if ( alpha < 0 || beta < 0){
                        std::cerr << "Generalized normal PDF: Incorrect parameters\n";
                        exit(2);
                }
                return beta/(2*alpha*tgamma(1/beta))*exp(-1*pow(abs(x-mu)/alpha, beta));
        }
double StochHMM::generalized_pareto_pdf (double x, double mu, double sigma, double xi)
Generalized Pareto probability distribution function
Parameters:
x Value
mu Location parameter
sigma Scale parameteer
xi Shape parameter
Definition at line 898 of file PDF.cpp.
{
                if (xi >= 0 && x < mu){
                        std::cerr << "Generalized pareto PDF: Incorrect parameters\n";
                        exit(2);
                }
                if (xi < 0 && ( x < mu || x > (mu-sigma/xi))){
                        std::cerr << "Generalized pareto PDF: Incorrect parameters\n";
                        exit(2);
                }
                if (xi ==0){
                        return 1 - exp(-1*((x-mu)/sigma));
                }
                return 1 - pow(1+((xi*(x-mu))/sigma), -1/xi);
        }
double StochHMM::geometric_pdf (int k, double p)
Geometric probability mass function
Parameters:
k Value or Trial of first success
p probability of success
Definition at line 147 of file PDF.cpp.
{
        return pow(1-p,k-1) * p;
    }
double StochHMM::gumbel_pdf (double x, double mu, double beta)
Gumbel Probability distribution function
Parameters:
x Value
mu Location parameter
beta Scale parameter
Definition at line 764 of file PDF.cpp.
{
                if (beta <= 0){
                        std::cerr << "Gumbel PDF: Incorrect parameters\n";
                        exit(2);
                }
                double z = (x-mu)/beta;
                return (1/beta)*exp(-1*(z)-exp(-1*z));
        }
double StochHMM::gumbel_type_one_pdf (double x, double a, double b)
Gumbel Type-2 Probability distribution function
Parameters:
x Value
a
b Shape
Definition at line 858 of file PDF.cpp.
{
                return a*b*exp(-1*(b*exp(-1*a*x))+a*x);
        }
double StochHMM::gumbel_type_two_pdf (double x, double a, double b)
Type 2 Gumbell Probability distribution function
Parameters:
x Value
a parameter
b shape parameter
Definition at line 714 of file PDF.cpp.
{
                if (x<=0 || x== INFINITY){
                        std::cerr << "Type 2 Gumbel PDF: Incorrect parameters\n";
                        exit(2);
                }
                return a*b*pow(x,-1*a-1) * exp(-1*b*pow(x,-1*a));
        }
double StochHMM::half_normal_pdf (double x, double sigma)
Half Normal probability distribution
Parameters:
x Value x>0
sigma Standard Deviation sigma>0
Definition at line 587 of file PDF.cpp.
{
                if (x <= 0 || sigma <= 0){
                        std::cerr << "Half Normal PDF: Incorrect parameters\n";
            exit(2);
                }
                return sqrt(2)/(sigma*sqrt(PI)) * exp(-1* pow(x,2)/(2*pow(sigma,2)));
        }
double StochHMM::hyperbolic_secant_pdf (double x)
Hyperbolic secant probability distribution function
Parameters:
x Value
Definition at line 801 of file PDF.cpp.
{
                return 0.5*pow(cosh((PI/2)*x),-1);
        }
double StochHMM::hypergeometric_pdf (int k, int n, int N, int m)
Hypergeometric Cumulative Distribution Function
Parameters:
k Value or Number of successes
n Number of draws from Population
N Size of population
m Number of successes in Population
Definition at line 76 of file PDF.cpp.
References StochHMM::bin_coef().
{
        return (bin_coef(m, k)*bin_coef(N-m,n-k))/bin_coef(N, n);
    }
double StochHMM::inv_gamma_pdf (double x, double alpha, double beta)
Inverse Gamma probability distribution
Parameters:
x Value x>0
alpha Shape parameter x>0
beta Scale parameter b>0
Definition at line 576 of file PDF.cpp.
{
                if (x <= 0 ||  alpha <= 0 || beta <= 0){
                        std::cerr << "Inverse Gamma PDF: Incorrect parameters\n";
            exit(2);
                }
                return (pow(beta,alpha)/tgamma(alpha))*pow(x,-1*alpha-1)*exp(-beta/x);
        }
double StochHMM::inv_gaussian_pdf (double x, double mu, double lambda)
Inverse Gaussian probability distribution
Parameters:
x Value x>0
mu Average u>0
lambda Shape parameter l>0
Definition at line 599 of file PDF.cpp.
{
                if (x <= 0 || mu <= 0 || lambda <= 0){
                        std::cerr << "Inverse Gaussian PDF: Incorrect parameters\n";
            exit(2);
                }
                return sqrt(lambda/(2*PI*pow(x, 3))) * exp((lambda*pow(x-mu,2))/(2*pow(mu,2)*x));
        }
double StochHMM::inverse_chi_squared_pdf (double x, double v)
Inverse-Chi-squared probability distribution function
Parameters:
x Value x>0
v v>0
Definition at line 440 of file PDF.cpp.
{
        if ( x <= 0 || v <= 0 ){
            std::cerr << "Inverse Chi squared PDF: Incorrect parameters\n";
            exit(2);
        }
        return (powf(2, -1*v/2)*powf(x, -1*(v/2)-1)*exp(-1/(2*x)))/tgamma(v/2);
    }
double StochHMM::kumaraswamy_pdf (double x, double a, double b)
Kumaraswamy probability distribution function
Parameters:
x
a Shape parameter
b Shape parameter
Definition at line 298 of file PDF.cpp.
{
        if (a <= 0 || b <= 0 || x < 0 || x > 1.0 ){
            std::cerr << "Kumaraswamy PDF:  Incorrect parameters\n";
            exit(2);
        }
        return a * b * powf(x, a-1) * powf((1 - powf(x, a)),b-1);
    }
double StochHMM::laplace_pdf (double x, double mu, double b)
Laplace Probability distribution function
Parameters:
x Value
mu Location Parameter
b Shape parameter
Definition at line 810 of file PDF.cpp.
{
                return 1/(2*b) * exp( -1 * abs(x-mu)/b);
        }
double StochHMM::levy_pdf (double x, double mu, double scale)
Levy probability distribution function
Parameters:
x Value x>= mu and x<INFINITY
mu location parameter
scale scale parameter C>0
Definition at line 611 of file PDF.cpp.
{
                if (x < mu || x == INFINITY || scale <= 0){
                        std::cerr << "Levy PDF: Incorrect parameters\n";
            exit(2);
                }
                return sqrt(scale/(2*PI)) * (exp((-1*scale)/(2*(x-mu)))/pow(x-mu,1.5));
        }
double StochHMM::log_cauchy_pdf (double x, double mu, double sigma)
Log Cauchy probability distribution function
Parameters:
x Value X>0 X<INFINITY;
mu Location
sigma scale parameter
Definition at line 623 of file PDF.cpp.
{
                if (x <= 0 || sigma <= 0 || x== INFINITY){
                        std::cerr << "Log Cauchy PDF: Incorrect parameters\n";
            exit(2);
                }
                return (1/(x*PI))*(sigma/(pow(log(x-mu),2)+pow(sigma,2)));
        }
double StochHMM::log_laplace_pdf (double x, double mu, double b)
Log Laplace probability distribution function
Parameters:
x Value
mu parameter
b parameter
Definition at line 635 of file PDF.cpp.
{
                if (x < mu){
                        return (1/(b*x))*exp(-1*((mu-log(x))/b));
                }
                return (1/(b*x))*exp(-1*((log(x)-mu)/b));
        }
double StochHMM::log_logistic_pdf (double x, double a, double b)
Log logistic probability distribution function
Parameters:
x Value
alpha scale parameter
beta shape parameter
Definition at line 647 of file PDF.cpp.
{
                if (x<0 || a < 0 || b < 0 || x == INFINITY){
                        std::cerr << "Log logistic PDF: Incorrect parameters\n";
                        exit(2);
                }
                return ((b/a)*pow(x/a,b-1))/pow(1+pow(x/a,b),2);
        }
double StochHMM::log_normal_pdf (double x, double mu, double sigma_sqrd)
Log Normal probability distribution function
Parameters:
x Value x>0 and x<INFINITY
mu Log scaled location parameter
sigma_sqrd Log scaled scaling parameter
Definition at line 660 of file PDF.cpp.
{
                if (x < 0 || x == INFINITY || sigma_sqrd <= 0){
                        std::cerr << "Log Normal PDF: Incorrect parameters\n";
                        exit(2);
                }
                return (1/(x*sqrt(2*PI*sigma_sqrd)))*exp(-1* (pow(log(x)-mu,2))/(2*sigma_sqrd));
        }
double StochHMM::logarithmic_pdf (int k, double p)
Logarithmic probability mass function
Parameters:
k Value
p Probability
Definition at line 155 of file PDF.cpp.
{
        if (k<1 || p==1.0 || p==0.0){
            std::cerr << "Logarithmic PDF Function:  k must be >=1, 0<p<1\n";
            exit(2);
        }
        return (1/log(1-p))*(pow(p,k)/k);
    }
double StochHMM::logistic_pdf (double x, double mu, double s)
Logistic Probability distribution function
Parameters:
x Value
mu Location parameter
s Shape parameter
Definition at line 818 of file PDF.cpp.
{
                return (1/(4*s))*pow(cosh((x-mu)/s),-2);
        }
double StochHMM::logit_normal_pdf (double x, double mu, double sigma)
Logit Normal probability distribution function
Parameters:
x Value
mu Mean
sigma Std. deviation
Definition at line 268 of file PDF.cpp.
References StochHMM::logit().
{
        if (x >= 1.0 || x <= 0.0 || sigma <= 0.0){
            std::cerr << "Logit Normal PDF: Incorrect parameters\n";
            exit(2);
        }
        return (1/(sigma*sqrtf(2*PI)))*exp(-1*pow((logit(x)-mu),2)/(2*pow(sigma,2)))*(1/(x*(1-x)));
    }
double StochHMM::maxwell_boltzman_pdf (double x, double a)
Maxwell-Boltzman Probability distribution function *a href = "http://en.wikipedia.org/wiki/MaxwellBoltzmann_distribution">
Parameters:
a Shape parameter a>0
x Value
Definition at line 139 of file PDF.cpp.
{
        return sqrtf(2/PI)*(pow(x,2)*exp(-1*pow(x,2)/(2*pow(a, 2))))/pow(a,3);
    }
double StochHMM::multivariate_ewens_pdf (const std::vector< double > & x, const double theta)
Multivariate Ewen's probability distribution function
Parameters:
x # of individual allele represented in sample
theta Parameter: details of evolutionary model
Definition at line 943 of file PDF.cpp.
{
                double n = factorial(x.size());
                double d(theta);
                for (size_t i=0; i < x.size() -1 ; ++i){
                        d *= theta + i;
                }
                double prob=1;
                for(size_t i=0; i < x.size() ; ++i){
                        prob*= pow(theta,x[i]) / (pow(i,x[i]) * factorial(x[i]));
                }
                return (n/d) * prob;
        }
double StochHMM::nakagami_pdf (double x, double mu, double w)
Nakagami probability distribution function
Parameters:
x Value
mu shape parameter
w spread parameter
Definition at line 689 of file PDF.cpp.
{
                if (x<=0 || mu < 0.5 || w <=0){
                        std::cerr << "Nakagami PDF: Incorrect parameters\n";
                        exit(2);
                }
                return (pow(2*mu,2)/(tgamma(mu)*pow(w, mu)))*pow(x,2*mu-1)*exp(-1*(mu/w)*pow(x,2));
        }
double StochHMM::negative_binomial_pdf (int k, int r, double p)
Negative binomial probability mass function
Parameters:
r Value or Number of failures until experiment stopped
p Success probability in each experiment
Definition at line 167 of file PDF.cpp.
References StochHMM::bin_coef().
{
        if (r<=0 || p<0.0 || p > 1.0){
            std::cerr << "Negative Binomial PMF: Incorrect parameters\n";
            exit(2);
        }
        return bin_coef(k+r-1, k)*pow(1-p,r)*pow(p,k);
    }
double StochHMM::normal_pdf (double x, double mu, double sigma)
Normal probability distribution function
Parameters:
x Value
mu Location parameter(mean)
sigma Scaling parameter (standard deviation)
Definition at line 832 of file PDF.cpp.
Referenced by StochHMM::standard_normal_pdf().
{
                if (sigma <= 0){
                        std::cerr << "Normal PDF: Incorrect parameters\n";
                        exit(2);
                }
                return (1/(sigma*sqrt(2*PI)))* exp(-1*pow(x-mu, 2)/(2*pow(sigma, 2)));
        }
double StochHMM::pareto_pdf (double x, double alpha, double x_m)
Pareto probability distribution function
Parameters:
x Value
alpha shape parameter
x_m scale parameter
Definition at line 673 of file PDF.cpp.
{
                if ( alpha <= 0 || x_m <= 0){
                        std::cerr << "Pareto PDF: Incorrect parameters\n";
                        exit(2);
                }
                if (x<x_m){
                        return 1;
                }
                return pow(x_m/x, alpha);
        }
double StochHMM::poisson_pdf (int k, double lambda)
Poisson probability mass function
Parameters:
k Trial of first success
lambda Probability of success
Definition at line 179 of file PDF.cpp.
{
        if (k<0 || lambda<=0){
            std::cerr << "Poisson PMF: Incorrect parameters\n";
            exit(2);
        }
        return (pow(lambda,(double)k)* exp(-1*lambda))/factorial(k);
    }
double StochHMM::raised_cosine_pdf (double x, double mu, double s)
Raised cosine probability distribution function
Parameters:
mu
s S>0
x u-s<=x<=u+s
Definition at line 310 of file PDF.cpp.
{
        if (s <= 0 || x < mu-s || x > mu+s){
            std::cerr << "Raised cosine PDF:  Incorrect parameters\n";
            exit(2);
        }
        return 1/(2*s)*(1+cosf(PI*(x-mu)/s));
    }
double StochHMM::rayleigh_pdf (double x, double sigma)
Rayleigh probability distribution function
Parameters:
x Value x>=0 and x<INFINITY
sigma Mode
Definition at line 702 of file PDF.cpp.
{
                if (x<0 || x == INFINITY || sigma <= 0){
                        std::cerr << "Rayleigh PDF: Incorrect parameters\n";
                        exit(2);
                }
                return (x/pow(sigma, 2))*exp(-1*(pow(x,2))/(2*pow(sigma,2)));
        }
double StochHMM::scaled_inverse_chi_squared_pdf (double x, double v, double sigma_sqrd)
Scaled Inverse Chi-squared probability distribution function
Parameters:
x Value x>0
v v>0
sigma_sqrd sigma_sqrd>0
Definition at line 453 of file PDF.cpp.
{
        if (x <= 0 || v<=0 || sigma_sqrd <= 0 ){
            std::cerr << "Scaled Inverse Chi-squared PDF: Incorrect paramenters\n";
            exit(2);
        }
        double numerator = powf(sigma_sqrd*(v/2),v/2);
        numerator *= exp((-1*v*sigma_sqrd)/(2*x));
        double denominator = tgamma(v/2);
        denominator *= powf(x, 1+(v/2));
        return numerator/denominator;
    }
double StochHMM::standard_normal_pdf (double x)
Standard Normal probability distribution function
Parameters:
x Value
Definition at line 824 of file PDF.cpp.
References StochHMM::normal_pdf().
{
                return normal_pdf(x, 0, 1);
        }
double StochHMM::students_t_pdf (double x, double v)
Student's t-probability distribution function
Parameters:
x Value
v Degrees of freedom
Definition at line 844 of file PDF.cpp.
{
                if (v<=0){
                        std::cerr << "Student's t-PDF: Incorrect parameters\n";
                        exit(2);
                }
                double i = tgamma((v+1)/2)/(sqrt(v*PI)*tgamma(v/2));
                return i * pow(1+(pow(x,2)/v),-1*(v+1)/2);
        }
double StochHMM::triangular_pdf (double x, double a, double b, double c)
Triangular probability distribution function
Parameters:
a Real number
b a<b
c a<=c<=b
x a<=x<=b
Definition at line 323 of file PDF.cpp.
{
        if (b<=a || c<=a || c>=b){
            std::cerr << "Triangular PDF:  Incorrect parameters\n";
            exit(2);
        }
        if (x >= a && x <= c){
            return 2*(x-a)/((b-a)*(c-a));
        }
        else if (x > c && x <= b){
            return 2*(b-x)/((b-a)*(b-c));
        }
        else{
            return 0;
        }
    }
double StochHMM::truncated_normal_pdf (double x, double mu, double sd, double a, double b)
Truncated Normal probability distribution function
Parameters:
a minimum value
b maximum value
mu Mean
sd Standard deviation
x Value
Definition at line 349 of file PDF.cpp.
{
        if (sd<0 || x < a || x > b){
            std::cerr << "Truncated normal PDF:  Incorrect paramenters\n";
            exit(2);
        }
        double alpha = (a-mu)/sd;
        double beta  = (b-mu)/sd;
        double xi = (x-mu)/sd;
        double alpha_cdf = (0.5*(1+erf((alpha-mu)/sqrt(2*pow(sd,2)))));
        double beta_cdf = (0.5*(1+erf((beta-mu)/sqrt(2*pow(sd,2)))));
        double z = beta_cdf - alpha_cdf;
        return (0.5*(1+erf((xi-mu)/sqrt(2*pow(sd,2)))))/(sd * z);
    }
double StochHMM::u_quadratic_pdf (double x, double a, double b)
U-quadratic probability distribution function
Parameters:
a
b
x
Definition at line 371 of file PDF.cpp.
{
        if (b <= a || x < a || x > b){
            std::cerr << "U-quadratic PDF: Incorrect parameters\n";
            exit(2);
        }
        double alpha = 12 / powf(b-a, 3);
        double beta = (b + a)/2;
        return alpha * powf(x-beta, 2);;
    }
double StochHMM::weibull_distribution (double x, double lambda, double k)
Weibull Probability distribution function
Parameters:
x value
lambda scale parameter
k shape parameter
Definition at line 726 of file PDF.cpp.
{
                if ( x==INFINITY || lambda <= 0 || k <= 0){
                        std::cerr << "Weibull PDF: Incorrect parameters\n";
                        exit(2);
                }
                if (x <0){
                        return 0.0;
                }
                return (k/lambda)*pow(x/lambda,k-1)*exp(-1*(pow(x/lambda, k)));
        }
double StochHMM::wigner_semicircle_pdf (double x, double r)
Wigner semicircle probability distribution function
Parameters:
r radius R>0
x value
Definition at line 386 of file PDF.cpp.
{
        if (r<=0){
            std::cerr << "Wigner semicircle PDF: Incorrect parameters\n";
            exit(2);
        }
        return (2/(PI*powf(r, 2)))*sqrtf(powf(r, 2) - powf(x, 2));
    }
double StochHMM::yule_simon_pdf (int k, double p)
Yule-Simon probability mass function
Parameters:
k
p Shape parameter
Definition at line 191 of file PDF.cpp.
{
        if (k<1 || p<=0.0){
            std::cerr << "Yule-Simon PMF: Incorrect parameters\n";
            exit(2);
        }
        return p*beta(k, p+1);
    }
double StochHMM::zipf_mandelbrot_pdf (int k, int N, double s, double q)
Zipf-Mandelbrot probability mass function
Parameters:
k The rank of element
N Number of elements
s Shape parameter (Exponent value)
q Shape parameter
Definition at line 223 of file PDF.cpp.
{
        if (k<1 || N<1 || s<=0.0 || q<0.0){
            std::cerr << "Zipf's PMF: Incorrect parameters\n";
            exit(2);
        }
        double pmf = 1/pow((double)k+q,s);
        double denom(0.0);
        for (int n = 1; n < N; n++){
            denom+=1/pow((double)n+q, s);
        }
        return pmf/denom;
    }
double StochHMM::zipf_pdf (int k, int N, double s)
Zipf probability mass function
Parameters:
k The rank of element
N Number of elements
s Shape parameter (Exponent value)
Definition at line 204 of file PDF.cpp.
{
        if (k<1 || N<1 || s<=0.0){
            std::cerr << "Zipf's PMF: Incorrect parameters\n";
            exit(2);
        }
        double pmf = 1/pow((double)k,s);
        double denom(0.0);
        for (int n = 1; n < N; n++){
            denom+=1/pow((double)n, s);
        }
        return pmf/denom;
    }